### ISSUE TITLE
Unable to delete files

### ISSUE THREAD

**Issue by amitm29** [deansyd/icloud_storage#11]
I am not able to delete files stored on iCloud storage using the delete function. The function doesn't throw any error, but listFiles as well as watchFiles still returns that file, which i just deleted.

Can you please confirm, if delete operation takes some time to reflect, and if yes then how much?

**Comment by REKURDennis** [comment]
I have the same problem. I don't know the reason behind it, but the native code cannot find the file and therefore also not remove it, so soon as the is an underscore in the filename.

**Comment by REKURDennis** [comment]
It seems you have to download the files first, before you can delete them. The list shows you all files in the iCloud. But I was only able to delete the ones I either uploaded from that device, or downloaded to the current device. Can anybody confirm, that this is the normal behaviour?

**Comment by amitm29** [comment]
@REKURDennis You're correct. I am able to delete the files after downloading them.

**Comment by deansyd** [comment]
This has been fixed in 0.2.3. Thanks for reporting this bug.
