### ISSUE TITLE
Where does the data gets stored?

### ISSUE THREAD

**Issue by ayaanpathan** [deansyd/icloud_storage#13]
Hi, 

Thank you for this plugin. I implemented this in my app and it worked fine. I checked my user's iCloud but the file was not there. Can you help me with this? as to where the file gets stored? The user's cloud or the app's cloud?

**Comment by deansyd** [comment]
Please refer to the apple doc as per referenced in the readme. (https://developer.apple.com/icloud/documentation/data-storage)
