### ISSUE TITLE
InvalidArgumentException: invalid destination relative path

### ISSUE THREAD

**Issue by ivangalkindeveloper** [deansyd/icloud_storage#14]
Hello
Thanks for the package, but I haven't been able to enjoy even one method working yet.
I need to upload a jsin file to a user's iCloud.
I made an iСloud container, connected it in Xcode.
Tried to download and saw an exception message in the console:
`InvalidArgumentException: invalid destination relative path`

What I would not prescribe in the destinationRelativePath field is the same script. Even if I do not specify this field.
What could be the problem?

Code:
```import 'dart:async';
import 'dart:io';
import 'package:breminder/constants.dart';
import 'package:breminder/services/export_service.dart';
import 'package:breminder/view/widgets/dialogs/export_dialog.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:icloud_storage/icloud_storage.dart';

class ICloudExport extends StatefulWidget {
  const ICloudExport({Key key}) : super(key: key);

  @override
  State<ICloudExport> createState() => _ICloudExportState();
}

class _ICloudExportState extends State<ICloudExport> {
  ICloudStorage _iCloudStorage;
  StreamSubscription<List<ICloudFile>> _filesUpdateSub;
  StreamSubscription<double> _uploadProgressSub;
  String _fileName = "";

  bool _isICloudLoggedIn;
  bool _isLoading = true;
  bool _showError = false;
  String _errorDescription = "";

  @override
  void initState() {
    this._initICloud();
    super.initState();
  }

  Future<void> _initICloud() async {
    try {
      this._iCloudStorage = await ICloudStorage.getInstance(Constants.iCloudContainer);
      await this._exportToICloud();
    } catch (error) {
      this._showError = true;
      this._errorDescription = error.toString();
      setState(() => this._isLoading = false);
    }
  }

  Future<void> _exportToICloud() async {
    setState(() {
      if (!this._isLoading) {
        this._isLoading = true;
      }
    });

    final File _exportFile = await ExportService.prepareFile();
    print(_exportFile.path.split("/").last);

    try {
      await this._iCloudStorage.startUpload(
            filePath: _exportFile.path,
            // destinationRelativePath: _exportFile.path.split("/").last,
            onProgress: (Stream<double> stream) {
              print("PRINT HERE");
              this._uploadProgressSub = stream.listen(
                (double progress) => print('Upload File Progress: $progress'),
                onDone: () {
                  this._fileName = _exportFile.path.split("/").last.split(".").first;
                  print("iCloud Export Success: $_fileName");
                },
                onError: (dynamic error) {
                  this._showError = true;
                  this._errorDescription = error.toString();
                },
                cancelOnError: true,
              );
            },
          );
    } catch (error) {
      if (error is PlatformException) {
        if (error.code == PlatformExceptionCode.iCloudConnectionOrPermission) {
          print(
              'Platform Exception: iCloud container ID is not valid, or user is not signed in for iCloud, or user denied iCloud permission for this app');
        } else if (error.code == PlatformExceptionCode.fileNotFound) {
          print('File not found');
        } else {
          print('Platform Exception: ${error.message}; Details: ${error.details}');
        }
      } else {
        print(error.toString());
      }
      this._showError = true;
      this._errorDescription = error.toString();
    }

    setState(() => this._isLoading = false);
  }

  @override
  Widget build(BuildContext context) {
    return ExportDialog(
      asset: Constants.iCloudBig,
      title: "iCloud",
      isLoggedIn: this._isICloudLoggedIn,
      logInTextDescription: "Please log in to Apple ID to export to iCloud  😔",
      logInButtonDescription: "Log In",
      logInOnPressed: this._initICloud,
      successDescription: "BReminder file success exported to your iCloud.\nFile: ${this._fileName}",
      successButtonDescription: "Done",
      succesOnPressed: () => Navigator.pop(context),
      showError: this._showError,
      errorDescription: this._errorDescription,
      errorButtonDescription: "Try again",
      errorOnPressed: this._exportToICloud,
      isLoading: this._isLoading,
    );
  }
}

**Comment by deansyd** [comment]
What is the value of `_exportFile.path`?

**Comment by ivangalkindeveloper** [comment]
> What is the value of `_exportFile.path`?

`/Users/ivangalkin/Library/Developer/CoreSimulator/Devices/EAF138A5-42BD-414E-926D-A35528383068/data/Containers/Data/Application/EDDE0B2E-01DB-4E63-80E8-DD11FA08E6A5/Documents/BReminder_export_2022-04-03 18:11:55.json`

**Comment by deansyd** [comment]
Colon is not allowed in the file name.

**Comment by ivangalkindeveloper** [comment]
> 

Changed the file name, the download actually started.
`flutter: /var/mobile/Containers/Data/Application/6DCB09E4-128B-4637-8704-7E24FA7AC25C/Documents/BReminder_export_2022-04-04T20-07-20.json`

Current code:
```
  Future<void> _exportToICloud() async {
    if (this._isLoading == false) {
      setState(() => this._isLoading = true);
    }

    final File _exportFile = await ExportService.prepareFile();
    print(_exportFile.path);

    try {
      await this._iCloudStorage.startUpload(
            filePath: _exportFile.path,
            destinationRelativePath: "./BReminder/${_exportFile.path.split("/").last}",
            onProgress: (Stream<double> stream) {
              this._uploadProgressSub = stream.listen(
                (double progress) => print('Upload File Progress: $progress'),
                onDone: () {
                  this._fileName = _exportFile.path.split("/").last.split(".").first;
                  setState(() => this._isLoading = false);
                  print("iCloud Export Success: $_fileName");
                },
                onError: (dynamic error) {
                  this._showError = true;
                  this._errorDescription = error.toString();
                },
                cancelOnError: true,
              );
       
            },
          );
    } catch (error) {
      this._showError = true;
      this._errorDescription = error.toString();
      setState(() => this._isLoading = false);
    }
  }
```
Another problem appeared:
Simulator:
The stream I'm listening to for uploads keeps saying "Upload File Progress: 0.0" and nothing happens.

Real device:
On a real device, it takes about 3-5 seconds to unload, but in the console I see "on cancel". Stream indeed initiates an "onDone" function for a short while I display a different interface.
I go to auCloud to which I uploaded the file and did not find it. Waited a day and still nothing showed up.

```
flutter: [/var/mobile/Containers/Data/Application/6DCB09E4-128B-4637-8704-7E24FA7AC25C/Documents/BReminder_export_2022-04-04T20-18-16.json]()
on listen
containerURL: [/private/var/mobile/Library/Mobile]() Documents[/iCloud]()~ivangalkindeveloper~breminder
2
flutter: Upload File Progress: 0.0
flutter: Upload File Progress: 95.0
flutter: Upload File Progress: 100.0
on cancel
flutter: iCloud Export Success: BReminder_export_2022-04-04T20-18-16
```

Therefore, a number of questions arose:

1) Why is this behavior on the simulator?
2) Did the file eventually load or is it an illusion?)
3) It's not entirely clear which path can be specified to put the file in the created folder, can you give an example of the path? Since which path I do not write - I get the error "InvalidArgumentException: invalid destination relative path"

**Comment by deansyd** [comment]
1. I got same issue with the simulator from time to time. The problem goes away after I reset the simulator (Device -> Erase All Content and Settings..). I believe this is the issue with simulator.
2. The file should be uploaded. Could you explain what you meant by 'I go to auCloud to which I uploaded the file and did not find it'? How did you go to iCloud and find it?
3. If you don't specify `destinationRelativePath`, it will take the file name and put it under the root dir of the iCloud container. For example, if the `filePath`  is /var/mobile/Containers/Data/Application/6DCB09E4-128B-4637-8704-7E24FA7AC25C/Documents/BReminder_export_2022-04-04T20-07-20.json. The file uploaded will be named as 'BReminder_export_2022-04-04T20-07-20.json'. If you do specify `destinationRelativePath`, make sure that path doesn't start of '/' or '.', and there's no ':' in it. In your code above, you should write `destinationRelativePath: "BReminder/${_exportFile.path.split("/").last}",`

**Comment by ivangalkindeveloper** [comment]
> 1. I got same issue with the simulator from time to time. The problem goes away after I reset the simulator (Device -> Erase All Content and Settings..). I believe this is the issue with simulator.
> 2. The file should be uploaded. Could you explain what you meant by 'I go to auCloud to which I uploaded the file and did not find it'? How did you go to iCloud and find it?
> 3. If you don't specify `destinationRelativePath`, it will take the file name and put it under the root dir of the iCloud container. For example, if the `filePath`  is /var/mobile/Containers/Data/Application/6DCB09E4-128B-4637-8704-7E24FA7AC25C/Documents/BReminder_export_2022-04-04T20-07-20.json. The file uploaded will be named as 'BReminder_export_2022-04-04T20-07-20.json'. If you do specify `destinationRelativePath`, make sure that path doesn't start of '/' or '.', and there's no ':' in it. In your code above, you should write `destinationRelativePath: "BReminder/${_exportFile.path.split("/").last}",`

After cleaning the simulator, the method began to work on the simulator.

Specified the path - destinationRelativePath: "BReminder/${_exportFile.path.split("/").last}".

The result is that the file is not visible in iCloud.
Attached video:
[https://disk.yandex.ru/client/disk?idApp=client&dialog=slider&idDialog=%2Fdisk%2F%D0%97%D0%B0%D0%BF%D0%B8%D1%81%D1%8C%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202022-04-05%20%D0%B2%2022.39.25.mov](url)

Maybe I'm doing something wrong? Or does your package not allow you to upload json files to iCloud Drive?

**Comment by ivangalkindeveloper** [comment]
> I couldn't open that link. Did you try to use the `gatherFiles` api to query from another device?

I'm sorry, try this link

https://disk.yandex.ru/i/kzLL4mR4yFy12Q

I'm trying to just upload a json-file to iCloud on the simulator, where I'm logged into the my test Apple ID. After uploading the file, I don't see it among the files in my test iCloud.
No, I have not used another device to view the downloaded files, but only on the current simulator I am trying to check the download of the file.

**Comment by deansyd** [comment]
You won't find it in the 'Files' app, as it is uploaded to the iCloud container for the app you are building. You'll need to check it using the `'gatherFiles'` or `'startDownload'` API from another device / simulator.

**Comment by ivangalkindeveloper** [comment]
I figured out the container, everything works excellent.
Thank you very much for such a nice package.

**Comment by faaqi** [comment]
Hi @ivangalkindeveloper , what do u mean by "I figured out the container," 

1. Were u able to fetch the file on other device?
2. Were u able to locate the file remotely on iCloud?

**Comment by ivangalkindeveloper** [comment]
> Привет@ivangalkindeveloper, что ты имеешь в виду под "Я разобрался с контейнером"?
> 
> 1. Удалось ли вам загрузить файл на другое устройство?
> 2. Удалось ли вам найти файл удаленно в iCloud?

This was more than two years ago, I don’t think I can answer your question anymore)

**Comment by faaqi** [comment]
Thanks. Figured this out :p @ivangalkindeveloper

**Comment by SunilKividor** [comment]
@faaqi were you able to figure this out ? How to remotely check the file on iCloud ?

**Comment by faaqi** [comment]
@SunilKividor 

On you iPhone :

1. Open Settings
2. Click Apple Id
3. Click iCloud icon
4. Click on Manage Account storage
5. Find your app in the list and open it, you'll see the files you created for iCloud storage.

**Comment by SunilKividor** [comment]
No its not present there. I am able to use the gather function and get the relative paths but cant see the files

**Comment by SunilKividor** [comment]
also is there something i need to add to info.plist too ?
@faaqi
