### ISSUE TITLE
txt file upload

### ISSUE THREAD

**Issue by gizemgizg** [deansyd/icloud_storage#16]
First of all, thank you very much for the package. I want to upload a txt file to icloud. I want to specify the name of this file myself. I didn't understand how to do it. Can you help me?

**Comment by deansyd** [comment]
Just specify the file name in the 'destinationRelativePath', such as 'xyz.txt'.

**Comment by gizemgizg** [comment]
thank you very much ✨ I have one last question. It uploaded successfully, but I can't see it in icloud drive. Is this normal?

**Comment by deansyd** [comment]
Maybe this will help you: https://github.com/deansyd/icloud_storage/issues/14#issuecomment-1090811902

**Comment by SunilKividor** [comment]
@gizemgizg were you able to check the files created on iCloud ? I am not able to find the files even after successful upload

**Comment by gizemgizg** [comment]
I managed to keep data as an object in cloudkit, not as a file. This plugin creates a record type called StorageItem. You can see the indexes in the StorageItem from the CloudKit Dashboard and since iCloud is hidden, you cannot see the data you saved, but you can see the value you saved with the key. I made some changes and used it in my project  @SunilKividor

**Comment by SunilKividor** [comment]
But this is not regarding cloudkit right ? This is about iCloud and app containers

**Comment by gizemgizg** [comment]
yes about the cloud kit

**Comment by gizemgizg** [comment]
Oh, sorry. I just realized. I didn't use this package, I had the same problem so I decided to use cloud_kit. I recommend it. @SunilKividor
