### ISSUE TITLE
onProgress callback of startUpload function gives 100% directly

### ISSUE THREAD

**Issue by nayanbabariya95** [deansyd/icloud_storage#17]
I want to upload my `getApplicationDocumentsDirectory()` into iCloud. And for that I am using following code:

```
final storage = await ICloudStorage.getInstance('iCloud.com.***');
              final dir = await getApplicationDocumentsDirectory();
              await storage.startUpload(filePath: dir.path, onProgress: (value) {
                value.listen((event) {
                  print('PROGRESS--------$event');
                });
              });
```

Here event is printing 100. and size of `getApplicationDocumentsDirectory()` is around 40MB.
If I go to iCloud from settings then it will showing initially 13 to 14 MB and by time it increase.
So that mean backup still in progress but this function directly tell us that it is completed.

**Comment by deansyd** [comment]
It won't upload all the contents inside the application documents directory. It will only create a folder in the iCloud container.

**Comment by nayanbabariya95** [comment]
@deansyd If it's not upload all the contents of app documents directory, then why my app showing 40MB data in iCloud settings? My app documents directory size is same. 40MB

**Comment by nayanbabariya95** [comment]
@deansyd Waiting for the solution or any temporary workaround.

**Comment by deansyd** [comment]
I haven't tested the scenario on uploading the entire directory. If you are sure all the contents in the directory are uploaded, the progress is probably only for the folder creation. I will test this case when I got time. The work around would be uploading individual files or zip the folder and upload it.

**Comment by nayanbabariya95** [comment]
Okay. thanks for your suggestion. please take your time and let me know your feedback

**Comment by nayanbabariya95** [comment]
@deansyd uploading single file is working perfectly, tested with 50MB, 100MB, 800MB.
But uploading entire folder seems not to be working. please check this issue.

**Comment by deansyd** [comment]
@nayanbabariya95, I just tested uploading a directory. It does upload all the contents of the directory but the progress only reports the status of the folder itself. The library wasn't intended for supporting uploading or downloading an entire directory. So this will not be fixed for now. You can use those workarounds I suggested earlier or you are welcome to contribute a PR to get his feature implemented.

**Comment by nayanbabariya95** [comment]
@deansyd Thanks for review. I want to know for my case. I need to upload 3 to 4 files in iCloud, so how can I know all the four files are uploaded? because if I upload them separate, then `onProgress`callback will also different. Any way to merge those all callback and listen on a single time?

**Comment by deansyd** [comment]
You can merge the progress streams into a single stream using StreamZip https://pub.dev/documentation/async/latest/async/StreamZip-class.html
