### ISSUE TITLE
Use the reccomended plugin_platform_interface package / PlatformInterface abstraction

### ISSUE THREAD

**Issue by erf** [deansyd/icloud_storage#19]
I ran: `flutter create --template=plugin --platforms=ios .` and a set of new files were added:

That is:
```
lib/icloud_storage_method_channel.dart
lib/icloud_storage_platform_interface.dart
test/icloud_storage_method_channel_test.dart
```

In addition to a few modifications to existing files.

It seem that `icloud_storage_platform_interface` depends on the package: 

```
https://pub.dev/packages/plugin_platform_interface
```
Which adds the `PlatformInterface` which is recommended for platform interfaces.

I wonder if you would like to support this interface?

I found this whilst looking into supporting the `macos` platform.

**Comment by deansyd** [comment]
Release 2.0.0 is now supporting macOS.
