### ISSUE TITLE
NSMetadataQueryUbiquitousDocumentsScope is not included

### ISSUE THREAD

**Issue by changyiyao** [deansyd/icloud_storage#20]
For purpose that is to save files in `Documents/`, the only search scope `NSMetadataQueryUbiquitousDataScope` is too limited, why no consider include NSMetadataQueryUbiquitousDocumentsScope in search scopes?

**Comment by tmpfs** [comment]
Hi, just wondering is this the reason that when I upload to my iCloud container's "Documents" folder that they don't show up in Finder/Files?

I have tried everything to get them to show up in Finder/Files (bumping build number, changing container id, re-installing) but it doesn't seem to help.

**Comment by changyiyao** [comment]
@tmpfs The PR fixes the progress of uploading files under `Documents` folder. Without it, no progress are called back.

It's not aimed to show up files in Finder/Files App. But if you want to achieve that, `NSUbiquitousContainers` must be configured properly in `info.plist`.

**Comment by tmpfs** [comment]
Thanks for the clarification @changyiyao.

**Comment by deansyd** [comment]
This is now fixed in 2.1.0. Thanks for the PR and feedback.

**Comment by SunilKividor** [comment]
@tmpfs did u find any solution for your issue. I am facing the same right now and I am not sure where I did wrong. Not able to see the files on iCloud after successful uploads.

**Comment by tmpfs** [comment]
> @tmpfs did u find any solution for your issue. I am facing the same right now and I am not sure where I did wrong. Not able to see the files on iCloud after successful uploads.

Sadly not @SunilKividor , I wish it worked, I think that it's Apple bugs to be honest, I spent a long time trying to figure it out. If you do figure it out please let me know. Many people say change the bundle identifier but that breaks sooooo much stuff it's not reasonable.
