### ISSUE TITLE
flutter: Upload File Progress: 95.0

### ISSUE THREAD

**Issue by codewithevan** [deansyd/icloud_storage#22]
Not 100%

And no file is generated in ICLOUD

What is the reason

**Comment by codewithevan** [comment]
var filePath = join(await getDatabasesPath(), "database_none.db");
await iCloudStorage.startUpload(
      filePath: filePath,
      destinationRelativePath:
          DateTime.now().millisecondsSinceEpoch.toString() + '.db',
      onProgress: (stream) {
        var uploadProgressSub = stream.listen(
          (progress) => print('Upload File Progress: $progress'),
          onDone: () => print('Upload File Done'),
          onError: (err) => print('Upload File Error: $err'),
          cancelOnError: true,
        );
      },
    );

**Comment by mdynia111** [comment]
@codewithevan have you fixed the problem? the same issue happens on some physical devices for me

**Comment by SunilKividor** [comment]
@mdynia111 were u able to see the files on icloud after uploading ? I can see no files but i was able to gather and download
