### ISSUE TITLE
How to change this status to downloaded

### ISSUE THREAD

**Issue by 353715181** [deansyd/icloud_storage#23]
<img width="1144" alt="image" src="https://user-images.githubusercontent.com/67812636/200214085-dc6b3d35-5245-492a-94ab-67612c8749fc.png">
How to change this status to downloaded

**Comment by 353715181** [comment]
After reinstalling the app, the uploaded data is not downloaded.

**Comment by deanyatwork** [comment]
Close this one as it is a question for iOS.
