### ISSUE TITLE
get E_NAT when file doesn’t exist

### ISSUE THREAD

**Issue by zeewell** [deansyd/icloud_storage#26]
When I try to download a file that does not exist via `ICloudStorage.download`, I should get an `E_FNF` exception message, but instead I get `E_NAT`

The exception information as below:
```
PlatformException(E_NAT, Native Code Error, Error Domain=NSCocoaErrorDomain Code=4 "The file “note_version.dat” doesn’t exist." UserInfo={NSURL=file:///private/var/mobile/Library/Mobile%20Documents/XXXXX/data/db/note_version.dat}, null)
```

**Comment by deansyd** [comment]
The download api doesn't check whether the file exists or not. I suggest you to use gather api first to make sure the file you wish to download has been synced to the device.
