### ISSUE TITLE
Does it support NSURLSessionUploadTask?

### ISSUE THREAD

**Issue by delfme** [deansyd/icloud_storage#28]
On ios, downloading/uploading files via NSURLSessionUploadTask guarantees that task keeps running even if app is minimized.

For example, plugins such as flutter_uploader, flutter_downloder and aws amplify support the feature.

Does icloud_storage wrapper comes with NSURLSessionUploadTask/NSURLSessionDowloadTask support as well?

**Comment by deansyd** [comment]
It doesn't use the exact api you've mentioned, but it works in a very similar way. Please refer to the doc https://developer.apple.com/library/archive/documentation/General/Conceptual/iCloudDesignGuide/Chapters/DesigningForDocumentsIniCloud.html
