### ISSUE TITLE
File is not downloading.

### ISSUE THREAD

**Issue by Ansh-Rathod** [deansyd/icloud_storage#29]
Hi, there I've been using this plugin for uploading and downloading files to the cloud but there is a misunderstanding or errors I'm facing. please review the provided code.

download function.

```
filename = 'Sqlite.zip'
file is saved in root of the icloud storage

Future<void> downloadFile(
    String filename,
    Function(int downloadedValue, int totalValue) onProgress,
    bool isSqliteFile) async {
  final tempDir = await getTemporaryDirectory();

  await ICloudStorage.download(
    containerId: 'my container id',
    relativePath: filename,
    destinationFilePath: tempDir.path + '/' + filename, <------- this line (i changed this line with  only tempDir.path but not working) 
    onProgress: (stream) {
      stream.listen(
        (value) {
          print(value);
          // onProgress.call(value.toInt(), 23032);
        },
        onError: (err) => print('Download File Error: $err'),
      );
    },
  );

  print(await File('${tempDir.path}/$filename').exists());

  var name = '${tempDir.path}/$filename';

```

the error I'm getting while running upper example and I'm not getting following error with only `destinationFilePath: tempDir.path`

```
Download File Error: PlatformException(E_NAT, Native Code Error, Error Domain=NSCocoaErrorDomain Code=512 "“sqlite.zip” couldn’t be copied to “Caches”." UserInfo={NSSourceFilePathErrorKey=/Users/anshrathod/Library/Developer/CoreSimulator/Devices/3974F62B-055C-4C67-9289-87D0C1E663F9/data/Library/Mobile Documents/iCloud~com~presence~app/sqlite.zip, NSUserStringVariant=(
    Copy
), NSDestinationFilePath=/Users/anshrathod/Library/Developer/CoreSimulator/Devices/3974F62B-055C-4C67-9289-87D0C1E663F9/data/Containers/Data/Application/75BEEB4C-8224-4F98-A681-87B004D81C3B/Library/Caches/sqlite.zip, NSFilePath=/Users/anshrathod/Library/Developer/CoreSimulator/Devices/3974F62B-055C-4C67-9289-87D0C1E663F9/data/Library/Mobile Documents/iCloud~com~presence~app/sqlite.zip, NSUnderlyingError=0x600002756280 {Error Domain=NSPOSIXErrorDomain Code=20 "Not a directory"}}, null)
flutter: false

```

both ways file is not saving in the tempDir.

**Comment by Allenxuxu** [comment]
> 你好，我一直在使用这个插件将文件上传并下载到云端，但我遇到了丢失或错误。请查看提供的代码。
> 
> 修改功能。
> 
> ```
> filename = 'Sqlite.zip'
> file is saved in root of the icloud storage
> 
> Future<void> downloadFile(
>     String filename,
>     Function(int downloadedValue, int totalValue) onProgress,
>     bool isSqliteFile) async {
>   final tempDir = await getTemporaryDirectory();
> 
>   await ICloudStorage.download(
>     containerId: 'my container id',
>     relativePath: filename,
>     destinationFilePath: tempDir.path + '/' + filename, <------- this line (i changed this line with  only tempDir.path but not working) 
>     onProgress: (stream) {
>       stream.listen(
>         (value) {
>           print(value);
>           // onProgress.call(value.toInt(), 23032);
>         },
>         onError: (err) => print('Download File Error: $err'),
>       );
>     },
>   );
> 
>   print(await File('${tempDir.path}/$filename').exists());
> 
>   var name = '${tempDir.path}/$filename';
> ```
> 
> 我在运行上面的示例时遇到了错误，并且没有得到以下错误`destinationFilePath: tempDir.path`
> 
> ```
> Download File Error: PlatformException(E_NAT, Native Code Error, Error Domain=NSCocoaErrorDomain Code=512 "“sqlite.zip” couldn’t be copied to “Caches”." UserInfo={NSSourceFilePathErrorKey=/Users/anshrathod/Library/Developer/CoreSimulator/Devices/3974F62B-055C-4C67-9289-87D0C1E663F9/data/Library/Mobile Documents/iCloud~com~presence~app/sqlite.zip, NSUserStringVariant=(
>     Copy
> ), NSDestinationFilePath=/Users/anshrathod/Library/Developer/CoreSimulator/Devices/3974F62B-055C-4C67-9289-87D0C1E663F9/data/Containers/Data/Application/75BEEB4C-8224-4F98-A681-87B004D81C3B/Library/Caches/sqlite.zip, NSFilePath=/Users/anshrathod/Library/Developer/CoreSimulator/Devices/3974F62B-055C-4C67-9289-87D0C1E663F9/data/Library/Mobile Documents/iCloud~com~presence~app/sqlite.zip, NSUnderlyingError=0x600002756280 {Error Domain=NSPOSIXErrorDomain Code=20 "Not a directory"}}, null)
> flutter: false
> ```
> 
> 两种方式的文件均未保存在 tempDir 中。



> Hi, there I've been using this plugin for uploading and downloading files to the cloud but there is a misunderstanding or errors I'm facing. please review the provided code.
> 
> download function.
> 
> ```
> filename = 'Sqlite.zip'
> file is saved in root of the icloud storage
> 
> Future<void> downloadFile(
>     String filename,
>     Function(int downloadedValue, int totalValue) onProgress,
>     bool isSqliteFile) async {
>   final tempDir = await getTemporaryDirectory();
> 
>   await ICloudStorage.download(
>     containerId: 'my container id',
>     relativePath: filename,
>     destinationFilePath: tempDir.path + '/' + filename, <------- this line (i changed this line with  only tempDir.path but not working) 
>     onProgress: (stream) {
>       stream.listen(
>         (value) {
>           print(value);
>           // onProgress.call(value.toInt(), 23032);
>         },
>         onError: (err) => print('Download File Error: $err'),
>       );
>     },
>   );
> 
>   print(await File('${tempDir.path}/$filename').exists());
> 
>   var name = '${tempDir.path}/$filename';
> ```
> 
> the error I'm getting while running upper example and I'm not getting following error with only `destinationFilePath: tempDir.path`
> 
> ```
> Download File Error: PlatformException(E_NAT, Native Code Error, Error Domain=NSCocoaErrorDomain Code=512 "“sqlite.zip” couldn’t be copied to “Caches”." UserInfo={NSSourceFilePathErrorKey=/Users/anshrathod/Library/Developer/CoreSimulator/Devices/3974F62B-055C-4C67-9289-87D0C1E663F9/data/Library/Mobile Documents/iCloud~com~presence~app/sqlite.zip, NSUserStringVariant=(
>     Copy
> ), NSDestinationFilePath=/Users/anshrathod/Library/Developer/CoreSimulator/Devices/3974F62B-055C-4C67-9289-87D0C1E663F9/data/Containers/Data/Application/75BEEB4C-8224-4F98-A681-87B004D81C3B/Library/Caches/sqlite.zip, NSFilePath=/Users/anshrathod/Library/Developer/CoreSimulator/Devices/3974F62B-055C-4C67-9289-87D0C1E663F9/data/Library/Mobile Documents/iCloud~com~presence~app/sqlite.zip, NSUnderlyingError=0x600002756280 {Error Domain=NSPOSIXErrorDomain Code=20 "Not a directory"}}, null)
> flutter: false
> ```
> 
> both ways file is not saving in the tempDir.

I encountered the same problem. How did you solve it?
