### ISSUE TITLE
Issues with upload/download

### ISSUE THREAD

**Issue by iosephmagno** [deansyd/icloud_storage#30]
Hello Dean, we have just made this sample repo.
https://github.com/Ansh-Rathod/icloud_sample_rpo

Please check Readme, we reported there test results which show issues with both upload/download.

Demo is simple, we fetch an image from web and then upload/download it to/from icloud.
We tested on emulator (ios 15.5) and real device (iphone pro 13 ios 16).

Can you please check whether this is a bug or our code?

**Comment by iosephmagno** [comment]
Forgot to mention that the same device where upload progress stalls can upload files to icloud when using whatsapp backup or system apps

**Comment by iosephmagno** [comment]
@deansyd we have found another wrapper attempt and tested it. We don't get the Error on download but upload progress issue occurs here as well and a 10s timeout is used inside the upload function to avoid an endless stall :-/
https://github.com/presence-app/icloud/blob/master/example/lib/main.dart

**Comment by delfme** [comment]
Other curious thing noticed. If we tap Upload button twice, the upload progress work on the second call (on first tap it always returns 100% instantly).

Download progress always show 100% instantly.

https://github.com/Ansh-Rathod/icloud_sample_rpo

**Comment by iosephmagno** [comment]
@deansyd please look at new example (vid below).
It seems that upload issue is with iOS16. This is why we got those differences between emulator and real phone. Emulator was ios15 and real phone was ios16.

You can check code here:
https://github.com/Ansh-Rathod/icloud_sample_rpo

With example, we tap buttons in following order:
1) fetch file from web
2) check that file is saved locally (it exists)
3) upload file to iCloud (it will upload and also delete file from device)
4) check that file is not saved locally (it doesnt exist)
5) download file from iCloud
6) check that file is saved locally (it exists)

It works with ios15, it doesnt with ios16 (upload stalls).

https://user-images.githubusercontent.com/83366073/212097260-b1d95669-9c28-492f-8bee-86756a9682c5.MP4

**Comment by iosephmagno** [comment]
Made more tests, it works with:
- ios 15.5

It doesnt work with:
- ios 16.1 (both emulator and device)
- ios 15.0
- much older ios versions (ie. ios 14)

**Comment by mny459** [comment]
@iosephmagno Hi, why closed? Any new? Think you
