### ISSUE TITLE
Unable to create files in subfolder

### ISSUE THREAD

**Issue by nivlaoh** [deansyd/icloud_storage#4]
Hi Dean,

Thanks for creating this library. I was looking for Flutter solution for uploading files to iCloud and I came across this. I managed to upload files to iCloud. However, I'm seeking more granular option to create subfolders and for the files to be placed in subfolder. And I saw that the startUpload function only retrieves the file name of the path from last slash passed in, hence not being able to create any subfolders in iCloud.

The purpose is for me to create different date folders to segregate the backups.

Is there intention to support this moving forward?

Thanks.

Flutter version: 2.0.5
icloud_storage version: 0.2.0

**Comment by deansyd** [comment]
Hi @nivlaoh, there's no plan to implement subfolders creations yet. For your use case, I suggest renaming the file with the backup date affixed on upload. You can pass this new name to the optional 'destinationFileName' parameter in the 'startUpload' function.

**Comment by nivlaoh** [comment]
I see. Thanks for your response.
