### ISSUE TITLE
How to get `iCloudContainerId` of the user

### ISSUE THREAD

**Issue by excogitatr** [deansyd/icloud_storage#5]
I am trying to build an app with the option to sync the data with the user's iCloud. How to get the `iCloudContainerId` of the particular user's iCloud account?

**Comment by deansyd** [comment]
The iCloud Container ID is not specific to any user's account, but to your App ID. Please refer to https://pub.dev/packages/icloud_storage#how-to-set-up-icloud-container-and-enable-the-capability

**Comment by excogitatr** [comment]
@deansyd Can you explain where the data will be stored? Will it be in the respective user's iCloud account or any specific iCloud?
