### ISSUE TITLE
Null safety exception

### ISSUE THREAD

**Issue by aleripe** [deansyd/icloud_storage#7]
Hi, since I updated my app to sound null safety and Flutter 2.2.3, I get this exception when doing `listFiles`:

`type 'Future<List<String>?>' is not a subtype of type 'FutureOr<List<String>>' in type cast`

Am I doing something wrong or might it be a bug?

Cheers

**Comment by aleripe** [comment]
Changing the listFiles method to this works:

```
Future<List<String>?> listFiles() async {
  return await (_channel.invokeListMethod<String>(
    'listFiles', {'eventChannelName': ''}) as Future<List<String>?>);
}
```

**Comment by deanyatwork** [comment]
The listFiles api returns a future of non-nullable list. It appears that you've mistakenly modified the source code.

**Comment by deansyd** [comment]
The listFiles api returns a future of non-nullable list. It appears that you've mistakenly modified the source code.

**Comment by aleripe** [comment]
I've not changed anything... the problem ix exactly that you return a non-nullable list while it expects a nullable list. The change I've done aftwerwards was to make it work again. By the way, I have a local copy that works with that modification, so it's up to you whether you want to fix it or not. Cheers
