### ISSUE TITLE
[FeatureRequest] Callback for delete(String fileName)

### ISSUE THREAD

**Issue by aleripe** [deansyd/icloud_storage#8]
Is it possible to have a callback also for the `delete(String fileName)` method? I need to refresh my file list after deleting items but if I do immediately after the file is still there (as the future completes without waiting)...

Thanks!

**Comment by deansyd** [comment]
The delete api is an async method. Please use await.

**Comment by aleripe** [comment]
I have used await, obviously, but as you've written in the documentation "the future completes without waiting". I need to have a callback after the file has been deleted for real.
